//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BakimDurumu
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string TezgahName { get; set; }
        public string Durum { get; set; }
        public Nullable<int> TezgahID { get; set; }
    }
}
