//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezgahID_Name
    {
        public int Id { get; set; }
        public string TezgahId { get; set; }
        public string TezgahName { get; set; }
    }
}
