//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uretim_Table
    {
        public int ID { get; set; }
        public int Tezgah_ID { get; set; }
        public long Uretim_Adet { get; set; }
        public string Uretim_Tarih { get; set; }
    }
}
